### PR TITLE
Various changes merged from 17.2 & Change as per Ticket 38425

### PR DESCRIPTION
**Pull request by labkey-bpatel**

### CODE REVIEW

**Comment by labkey-bpatel** [comment]
This fb is created from wnprc18.3_master. Conflicts (around BaseColumnInfo) are now resolved in this fb, so that it is mergable to release19.2-SNAPSHOT (this leaves wnprc18.3_master as-is without having to backport changes from 19.2).

**Comment by labkey-jeckels** [comment]
@labkey-bpatel Can you rename this branch to meet the 19.2_fb_ prefix naming convention so we can see if builds on TeamCity will be happy there before we commit?

**Comment by labkey-jeckels** [comment]
Or will that be the wrong mix of 18.3 and 19.2 code?

**Comment by labkey-bpatel** [comment]
@labkey-jeckels think it should be fine to rename to 19.2_fb_ prefix, code in this branch should be compatible with 19.2 anyway. will go ahead and rename..

**Pull request closed without merging**
