### PR TITLE
JET and Data Entry updates

### PR DESCRIPTION
**Pull request by labkey-bpatel**
- Update to JET query to filter on non-genCredit accounts.
- Update Non-Animal Charges data entry to populate 'Debit Account' drop down w.r.t. charge date.
- New automated tests for the above changes & other test fixes.

### CODE REVIEW

**Comment by labkey-jeckels** [comment]
@labkey-bpatel GitHub is reporting that NonAnimalCharges.js has a conflict that needs to be resolved - can you handle this before I finish the review?

**Comment by dnicolalde** [comment]
When do you think you can have this conflict resolved? We are planning to update today production server. We can leave this fix for an update later in the week.

**Comment by labkey-bpatel** [comment]
@dnicolalde conflict was resolved this morning.
Waiting on Code Review and Feature Verification - depending on @labkey-jeckels and @labkey-sweta availability.

**Review by labkey-jeckels — APPROVED** [review]

**Comment by dnicolalde** [comment]
Merging the code changes. Thank you for your work.

**Pull request merged**
